Fix Ruby version in GitHub Actions workflow to avoid errors during setup
```
Error: Error: Unavailable version 3.4.0-preview2 for ruby on ubuntu-24.04
          You can request it at https://github.com/ruby/setup-ruby/issues
          Cause: Unexpected HTTP response: 404
    at /home/runner/work/_actions/ruby/setup-ruby/f26937343756480a8cb3ae1f623b9c8d89ed6984/dist/index.js:65021:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async body (/home/runner/work/_actions/ruby/setup-ruby/f26937343756480a8cb3ae1f623b9c8d89ed6984/dist/index.js:353:14)
```

see: https://github.com/ruby/racc/actions/runs/18798977070/job/53643662504